// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/**
 * @title IUltraVerifier
 * @notice Interface for Noir UltraPlonk proof verifier
 * @dev This interface is compatible with Noir-generated verifier contracts
 */
interface IUltraVerifier {
    /**
     * @notice Verify a zero-knowledge proof
     * @param _proof The proof bytes generated by Noir prover
     * @param _publicInputs Array of public inputs to the circuit
     * @return bool True if the proof is valid, false otherwise
     */
    function verify(bytes calldata _proof, bytes32[] calldata _publicInputs) external view returns (bool);
}
